export const APPLICATION_CLASS_NAMES = {
  root: 'application',
  frame: 'application__frame',
  workspace: 'application__workspace',
  canvasShell: 'application__canvas-shell',
  sidebar: 'application__sidebar',
  sidebarMain: 'application__sidebar-main',
  sidebarHeader: 'application__sidebar-header',
  sidebarList: 'application__sidebar-list',
  primaryButton: 'application__primary-button',
  primaryButtonSecondary: 'application__primary-button--secondary',
  panelTitle: 'application__panel-title',
  panelCaption: 'application__panel-caption',
  gasControl: 'application__gas-control',
  gasControlLabel: 'application__gas-control-label',
  gasSelect: 'application__gas-select',
  gasHint: 'application__gas-hint',
  workspaceTitle: 'application__workspace-title',
  workspaceMeta: 'application__workspace-meta',
  workspaceMetaItem: 'application__workspace-meta-item',
  workspaceMetaLabel: 'application__workspace-meta-label',
  workspaceMetaValue: 'application__workspace-meta-value',
  workspaceControls: 'application__workspace-controls',
  workspaceActions: 'application__workspace-actions',
  paletteItem: 'application__palette-item',
  paletteItemDisabled: 'application__palette-item--disabled',
  runtimePanel: 'application__runtime-panel',
  runtimeActions: 'application__runtime-actions',
  secondaryButton: 'application__secondary-button',
  resultsPreview: 'application__results-preview',
  resultsPreviewActions: 'application__results-preview-actions',
  resultsPreviewButton: 'application__results-preview-button',
  resultsPanel: 'application__results-panel',
  resultsSection: 'application__results-section',
  resultsTable: 'application__results-table',
  gasBadge: 'application__gas-badge',
  gasBadgeIdeal: 'application__gas-badge--ideal',
  gasBadgeReal: 'application__gas-badge--real',
  chart: 'application__chart',
  chartPlot: 'application__chart-plot',
  chartMain: 'application__chart-main',
  chartStage: 'application__chart-stage',
  chartSvg: 'application__chart-svg',
  chartYAxis: 'application__chart-y-axis',
  chartYAxisTicks: 'application__chart-y-axis-ticks',
  chartYAxisTick: 'application__chart-y-axis-tick',
  chartXAxisRow: 'application__chart-x-axis-row',
  chartAxisCorner: 'application__chart-axis-corner',
  chartXAxis: 'application__chart-x-axis',
  chartXAxisTicks: 'application__chart-x-axis-ticks',
  chartXAxisTick: 'application__chart-x-axis-tick',
  chartAxisLabel: 'application__chart-axis-label',
  chartAxisLabelX: 'application__chart-axis-label--x',
  chartAxisLabelY: 'application__chart-axis-label--y',
  chartEmpty: 'application__chart-empty',
  chartLegend: 'application__chart-legend',
  chartLegendItem: 'application__chart-legend-item',
  chartLegendSwatch: 'application__chart-legend-swatch',
  emptyState: 'application__empty-state',
  emptyStateTitle: 'application__empty-state-title',
  emptyStateText: 'application__empty-state-text',
  modal: 'application__modal',
  modalBackdrop: 'application__modal-backdrop',
  modalDialog: 'application__modal-dialog',
  modalHeader: 'application__modal-header',
  modalBody: 'application__modal-body',
  modalTabs: 'application__modal-tabs',
  modalTab: 'application__modal-tab',
  modalTabActive: 'application__modal-tab--active',
  modalClose: 'application__modal-close',
  dragGhost: 'application__drag-ghost',
  toastStack: 'application__toast-stack',
  toast: 'application__toast',
  toastSuccess: 'application__toast--success',
  toastError: 'application__toast--error',
} as const;

export const APPLICATION_LABELS = {
  title: 'Определение параметров истечения идеального и реальных газов при дросселировании',
  equipmentPanel: 'Оборудование',
  sensorsPanel: 'Датчики',
  runtimePanel: 'Параметры',
  resultsPanel: 'Результаты измерений',
  openResults: 'Открыть результаты',
  closeResults: 'Закрыть',
  gasLabel: 'Рабочий газ',
  barometer: 'Барометр',
  captureMeasurement: 'Снять измерение',
  measurementsTable: 'Таблица измерений',
  velocityChart: 'График скорости',
  emptyMeasurements: 'Снимите хотя бы одно измерение, чтобы построить график и открыть полные результаты.',
  emptyActiveGasMeasurements: 'Для выбранного газа ещё нет измерений.',
  emptyActiveGasMeasurementsHint: 'Измените положение вентиля и снимите хотя бы одну точку, чтобы построить график именно для этого газа.',
  emptyOtherGasMeasurementsHint: 'Для других газов история уже есть — полные результаты доступны по кнопке ниже.',
  modalScopeAll: 'Все',
  initialStatus: 'Соберите схему Lab6 и подтвердите переход к датчикам.',
  assemblyHelper: 'Разместите оборудование на поле и соберите корректную цепочку соединений.',
  instrumentsHelper: 'Перенесите датчики на валидные точки камер и проверьте комплектацию.',
  runningHelper: 'Регулируйте вентиль и снимайте измерения. График и выбор газа собраны справа.',
  assemblyConfirmedToast: 'Сборка подтверждена. Можно переходить к установке датчиков.',
  runningStartedToast: 'Установка запущена.',
  runningStoppedToast: 'Установка остановлена.',
  connectionSelfError: 'Нельзя соединить элемент с самим собой.',
  connectionBusyError: 'Один из выбранных портов уже занят.',
  connectionDuplicateError: 'Такое соединение уже существует.',
  connectionInvalidError: 'Не удалось построить корректное соединение между узлами.',
  sensorWrongPointError: 'Выбрана неверная точка установки датчика.',
  sensorWrongTypeError: 'Датчик не подходит для этого слота.',
  sensorOccupiedError: 'Слот уже занят.',
} as const;

export const APPLICATION_TEXTS = {
  sensorCount: 'шт.',
  barometerUnit: 'мм рт. ст.',
  pressureUnit: 'кПа',
  volumeUnit: 'м³/с',
} as const;

export const APPLICATION_NUMBERS = {
  framePadding: 24,
  animationFrameDelay: 0,
  millisecondsInSecond: 1000,
} as const;
