export const APPLICATION_CLASS_NAMES = {
  root: 'application',
  frame: 'application__frame',
  workspace: 'application__workspace',
  canvasShell: 'application__canvas-shell',
  sidebar: 'application__sidebar',
  sidebarHeader: 'application__sidebar-header',
  sidebarList: 'application__sidebar-list',
  primaryButton: 'application__primary-button',
  primaryButtonSecondary: 'application__primary-button--secondary',
  panelTitle: 'application__panel-title',
  panelCaption: 'application__panel-caption',
  gasControl: 'application__gas-control',
  gasControlLabel: 'application__gas-control-label',
  gasSelect: 'application__gas-select',
  gasHint: 'application__gas-hint',
  workspaceTitle: 'application__workspace-title',
  paletteItem: 'application__palette-item',
  paletteItemDisabled: 'application__palette-item--disabled',
  widget: 'application__widget',
  widgetValue: 'application__widget-value',
  widgetLabel: 'application__widget-label',
  runtimePanel: 'application__runtime-panel',
  runtimeActions: 'application__runtime-actions',
  secondaryButton: 'application__secondary-button',
  resultsPreview: 'application__results-preview',
  resultsPreviewButton: 'application__results-preview-button',
  resultsPanel: 'application__results-panel',
  resultsSection: 'application__results-section',
  resultsTable: 'application__results-table',
  gasBadge: 'application__gas-badge',
  gasBadgeIdeal: 'application__gas-badge--ideal',
  gasBadgeReal: 'application__gas-badge--real',
  chart: 'application__chart',
  chartEmpty: 'application__chart-empty',
  chartLegend: 'application__chart-legend',
  chartLegendItem: 'application__chart-legend-item',
  chartLegendSwatch: 'application__chart-legend-swatch',
  modal: 'application__modal',
  modalBackdrop: 'application__modal-backdrop',
  modalDialog: 'application__modal-dialog',
  modalHeader: 'application__modal-header',
  modalBody: 'application__modal-body',
  modalClose: 'application__modal-close',
  dragGhost: 'application__drag-ghost',
  toastStack: 'application__toast-stack',
  toast: 'application__toast',
  toastSuccess: 'application__toast--success',
  toastError: 'application__toast--error',
} as const;

export const APPLICATION_LABELS = {
  title: 'Определение параметров истечения идеального и реальных газов при дросселировании',
  equipmentPanel: 'Оборудование',
  sensorsPanel: 'Датчики',
  runtimePanel: 'Параметры',
  resultsPanel: 'Результаты измерений',
  openResults: 'Открыть результаты',
  closeResults: 'Закрыть',
  gasLabel: 'Рабочий газ',
  barometer: 'Барометр',
  captureMeasurement: 'Снять измерение',
  measurementsTable: 'Таблица измерений',
  velocityChart: 'График скорости от p2abs/p1abs',
  emptyMeasurements: 'Снимите хотя бы одно измерение, чтобы заполнить таблицу и построить график.',
  initialStatus: 'Соберите схему Lab6 и подтвердите переход к датчикам.',
  assemblyHelper: 'Разместите оборудование на поле и соберите корректную цепочку соединений.',
  instrumentsHelper: 'Перенесите датчики на валидные точки камер и проверьте комплектацию.',
  runningHelper: 'Следите за показаниями, регулируйте вентиль и сохраняйте точки измерений.',
  assemblyConfirmedToast: 'Сборка подтверждена. Можно переходить к установке датчиков.',
  runningStartedToast: 'Установка запущена.',
  runningStoppedToast: 'Установка остановлена.',
  connectionSelfError: 'Нельзя соединить элемент с самим собой.',
  connectionBusyError: 'Один из выбранных портов уже занят.',
  connectionDuplicateError: 'Такое соединение уже существует.',
  connectionInvalidError: 'Не удалось построить корректное соединение между узлами.',
  sensorWrongPointError: 'Выбрана неверная точка установки датчика.',
  sensorWrongTypeError: 'Датчик не подходит для этого слота.',
  sensorOccupiedError: 'Слот уже занят.',
} as const;

export const APPLICATION_TEXTS = {
  sensorCount: 'шт.',
  barometerUnit: 'мм рт. ст.',
  pressureUnit: 'кПа',
  volumeUnit: 'м³/с',
} as const;

export const APPLICATION_NUMBERS = {
  framePadding: 24,
  animationFrameDelay: 0,
  millisecondsInSecond: 1000,
} as const;
