export const APPLICATION_CLASS_NAMES = {
  root: 'application',
  frame: 'application__frame',
  workspace: 'application__workspace',
  canvasShell: 'application__canvas-shell',
  sidebar: 'application__sidebar',
  sidebarHeader: 'application__sidebar-header',
  sidebarList: 'application__sidebar-list',
  primaryButton: 'application__primary-button',
  primaryButtonSecondary: 'application__primary-button--secondary',
  panelTitle: 'application__panel-title',
  panelCaption: 'application__panel-caption',
  workspaceTitle: 'application__workspace-title',
  paletteItem: 'application__palette-item',
  paletteItemDisabled: 'application__palette-item--disabled',
  widget: 'application__widget',
  widgetValue: 'application__widget-value',
  widgetLabel: 'application__widget-label',
  runtimePanel: 'application__runtime-panel',
  dragGhost: 'application__drag-ghost',
  valveControls: 'application__valve-controls',
  valveButton: 'application__valve-button',
  toastStack: 'application__toast-stack',
  toast: 'application__toast',
  toastSuccess: 'application__toast--success',
  toastError: 'application__toast--error',
} as const;

export const APPLICATION_LABELS = {
  title: 'Лабораторная работа №6',
  equipmentPanel: 'Оборудование',
  sensorsPanel: 'Датчики',
  runtimePanel: 'Параметры',
  barometer: 'Барометр',
  stopwatch: 'Секундомер',
  initialStatus: 'Соберите схему Lab6 и подтвердите переход к датчикам.',
  valveOpen: 'Открыть',
  valveClose: 'Закрыть',
  assemblyHelper: 'Разместите оборудование на поле и соберите корректную цепочку соединений.',
  instrumentsHelper: 'Перенесите датчики на валидные точки камер и проверьте комплектацию.',
  runningHelper: 'Следите за показаниями и регулируйте вентиль в процессе работы установки.',
  assemblyConfirmedToast: 'Сборка подтверждена. Можно переходить к установке датчиков.',
  runningStartedToast: 'Установка запущена.',
  runningStoppedToast: 'Установка остановлена.',
  connectionSelfError: 'Нельзя соединить элемент с самим собой.',
  connectionBusyError: 'Один из выбранных портов уже занят.',
  connectionDuplicateError: 'Такое соединение уже существует.',
  connectionInvalidError: 'Не удалось построить корректное соединение между узлами.',
  sensorWrongPointError: 'Выбрана неверная точка установки датчика.',
  sensorWrongTypeError: 'Датчик не подходит для этого слота.',
  sensorOccupiedError: 'Слот уже занят.',
} as const;

export const APPLICATION_TEXTS = {
  sensorCount: 'шт.',
  barometerUnit: 'мм рт. ст.',
  pressureUnit: 'кПа',
  temperatureUnit: '°C',
  volumeUnit: 'м³/с',
} as const;

export const APPLICATION_NUMBERS = {
  framePadding: 24,
  animationFrameDelay: 0,
  valveStep: 1,
  millisecondsInSecond: 1000,
} as const;